---
title: "R Notebook"
output: html_notebook
---

```{r}
library(lubridate)
library(stringr)
library(googlesheets)
```



```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1,Encoding()) #access the 1st worksheet
```

```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
```

```{r}
library(stringr)
aa <- (str_sub(classSurvey[c(5)], 1, 3))
classSurvey[aa == "台北市",c("姓名")]
```

```{r}
cc<- classSurvey[aa == "台北市",c("姓名")]
class(cc)
cc$姓名[3]
```

```{r}
bb<-c("a","b","c")
bb[2]
```

```{r}
StuDF <- data.frame(StuID=c(1,2,3,4,5), name=c("小明","大雄","胖虎","小新","大白"), score=c(80, 60, 90, 70, 50))
StuDF 
```

```{r}
names(gsSurvey)
```

```{r}
gsSurvey$links$type
```

```{r}
names(StuDF)[2] <- c("姓名")
names(StuDF)
```

```{r}
names(StuDF) <- c("學號","姓名","成績")
names(StuDF)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student[c(4)])
```

```{r}
levels(student[c(4)]) <- c("小個子","小個子","小個子","小個子","小個子","中等個子","中等個子","高個子","高個子")
student$身高級距
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student[c(4)])[c(1:3)]<-c("(0,160]")
levels(student[c(4=)])==
```

```{r}
library(googlesheets)
#gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```
 1.1
```{r}
dim(classSurvey)
nrow(classSurvey)
ncol(classSurvey)
```

```{r}
class(classSurvey[c(4)])
classSurvey[c(4)] <- as.character(classSurvey[c(4)])
library(stringr)
classSurvey$年級 <- str_sub(classSurvey[c(4)],2,4)
classSurvey$年級 <- as.factor(classSurvey$年級)
levels(classSurvey$年級) <- c("大四及以上","大三","大二","大一")
```