---
title: "2018-12-04"
output: html_notebook
---

```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData %>%
  mutate_art(
    vars(學院, 書籍觀藏地, 書籍類別),
    funs(
      as.factor(.)
    )
  ) -> libraryData

libraryData %>%
  mutate(
    借閱時間=ymd_hms(借閱時間，tz="Asia/Taipei")
  ) -> libraryData
``` 

```{r}
## 1
max(libraryData$讀者借閱冊數)-> maxi
min(libraryData$讀者借閱冊數)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)
```


```{r}
## 1
max(libraryData$讀者借閱冊數)-> maxi
min(libraryData$讀者借閱冊數)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)
## 2
max(libraryData$入學年)-> maxi
min(libraryData$入學年)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)
## 3
max(libraryData$書籍上架年月)-> maxi
min(libraryData$書籍上架年月)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)
```

minMaxFun(x)
```{r}
minMaxFun <- function(x){
max(x)-> maxi
min(x)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)}
```

```{r}
minMaxFun(libraryData$讀者借閱冊數)->x1
x1
minMaxFun(libraryData$入學年)->y2
y2
minMaxFun(libraryData$書籍上架年月)->z3
z3
```


```{r}
minMaxFun2 <- function(x){
max(x)-> maxi
min(x)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)-> result
return(result)
}
```


```{r}
minMaxFun3 <- function(x){
max(x)-> maxi
min(x)-> mini
paste0("最大值： ",maxi, " 最小值： ",mini)
return(maxi)
}
```


```{r}
minMaxFun3(libraryData$讀者借閱冊數)-> x1
x1
minMaxFun3(libraryData$入學年)->y2
y2
minMaxFun3(libraryData$書籍上架年月)->z3
z3
```

```{r}
minMaxFun4 <- function(x){
max(x)-> maxi
min(x)-> mini
print(
  paste0("最大值： ",maxi, " 最小值： ",mini)
  ) 
return(maxi)
}
```

```{r}
minMaxFun4(libraryData$讀者借閱冊數)-> x1
x1
```

```{r}
!is.numeric(libraryData$學號)
!is.numeric(libraryData$書籍類別)
```

```{r}
not_numeric<- function(x){
  !is.numeric(x)
}
```

```{r}
not_numeric<- function(x){
  !is.numeric(x) -> result
  return(result)
}
```

```{r}
not_numeric(libraryData$學號)
```

### 練習：
找出屬於"人文學院"的子樣本。

```{r}
(libraryData$學院=="人文學院")-> logIndex
libraryData[logIndex,]-> subsample
```

找出屬於"社會科學院"的子樣本。

```{r}
(libraryData$學院=="社會科學院")-> logIndex
libraryData[logIndex,]-> subsample
```

```{r}
findMyCollege<-function(x){
  (libraryData$學院==x)-> logIndex
libraryData[logIndex,]-> subsample
return(subsample)
}
```

```{r}
findMyCollege("人文學院")-> sam1
nrow(sam1)
findMyCollege("社會科學院") -> sam2
nrow(sam2)
```

```{r}
libraryData %>%
  group_by(學院) %>%
  summarise(
    學院借閱冊數=length(學號)
  )
  
```

```{r}
libraryData %>%
  select(讀者借閱冊數,書籍出版日期) %>%
  summarise(
    讀者平均借閱冊數=mean(讀者借閱冊數),
    最小書籍出版日期=min(書籍出版日期),
    最大書籍出版日期=max(書籍出版日期)
  )
```